runtime: python37

handlers:
  - url: /static
    static_dir: static/
  - url: .*
    script: auto

env_variables:
  POSTGRESQL_CONNECTION_NAME: casino-307523:us-central1:casinodb
  POSTGRES_DB: [casinodb]
  POSTGRES_PASSWORD: [theowner559!]
  POSTGRES_USER: [howard]
  POSTGRES_HOST: [35.238.200.155]
